language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vesuvius/docker-course -f Dockerfile.dev .

script:
  - docker run -e CI=true vesuvius/docker-course npm run test -- --coverage